Repository rosenpass/rosenpass, pull requests merged in 2024-04, with the labels that each got.

#142 Add cookie mechanism
  Cargo.lock
  Cargo.toml
  papers/whitepaper.md
  rosenpass/Cargo.toml
  rosenpass/src/app_server.rs
  rosenpass/src/cli.rs
  rosenpass/src/config.rs
  rosenpass/src/hash_domains.rs
  rosenpass/src/main.rs
  rosenpass/src/msgs.rs
  rosenpass/src/protocol.rs
  rosenpass/tests/integration_test.rs
Labels: 🙋 Bounty claim, dos-resistance

#235 Port "rp" to Rust
  .github/workflows/nix.yaml
  Cargo.lock
  Cargo.toml
  flake.nix
  readme.md
  rosenpass/src/app_server.rs
  rp
  rp/Cargo.toml
  rp/src/cli.rs
  rp/src/exchange.rs
  rp/src/key.rs
  rp/src/main.rs
Labels: 🙋 Bounty claim, 💰 Rewarded

#293 rp: Load WireGuard SK into secret memory
  rp/src/key.rs
Labels: bug, rust-security
